name: PR Verify

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Format
        run: dotnet format --verbosity detailed --verify-no-changes
