name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish src/ECommerce.Api/ECommerce.Api.csproj --configuration Release --output artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: artifacts/
