name: CI

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish src/ECommerce.Api/ECommerce.Api.csproj --configuration Release --output artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy dev
    needs: build
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
    secrets: inherit
